name: Desktop App Build

on:
  push:
    branches: 
      - main

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: installing front dependencies
        run: |
          cd frontend
          yarn install
          yarn build
          
      - name: installing backend dependencies
        run: |
          cd backend
          yarn install
          cd ..
          move frontend/build backend
          
      
      - name: prepare for desktop app
        run: |
          cd backend
          yarn build-win64
      
      - name: release app
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: backend/dist/

  build_linux:
    needs: [build_windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: installing front dependencies
        run: |
          cd frontend
          yarn install
          yarn build
          
      - name: installing backend dependencies
        run: |
          cd backend
          yarn install
          cd ..
          cp -R frontend/build backend
          
      
      - name: prepare for desktop app
        run: |
          cd backend
          yarn build-linux
      
      - name: release app
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: backend/dist/
